FROM python:3.11

WORKDIR /app

ENV BACK_DIR=Modelos_ML/RegresionLineal/back

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY ${BACK_DIR}/requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY ${BACK_DIR}/train.py ./
COPY ${BACK_DIR}/main.py ./
COPY ${BACK_DIR}/models ./models

RUN python train.py

ENV PORT=8000

EXPOSE ${PORT}

CMD uvicorn main:app --host 0.0.0.0 --port ${PORT}
